package handlers

import (
	"encoding/json"
	"log"
	"net/http"
	"strings"
)

// ApiSubjectInfo는 API 응답을 위한 공통 구조체입니다.
// 코드, 명칭, 그리고 상위 코드(선택적)를 포함합니다.
type ApiSubjectInfo struct {
	SubjectCode string  `json:"subjectCode"`
	SubjectName string  `json:"subjectName"`
	ParentCode  *string `json:"parentCode,omitempty"` // 상위 코드가 없는 경우 JSON에서 생략됨
}

// --- 내신 데이터 구조 ---

// NaesinCurriculumClassification: 내신 '교과구분종류' (예: 일반 교과, 진로 선택 교과)
type NaesinCurriculumClassification struct {
	Code string // 예: "CLASS_COMMON"
	Name string // 예: "일반 교과"
}

// NaesinCurriculum: 특정 '교과구분종류'에 속하는 '교과' (예: 국어, 수학)
type NaesinCurriculum struct {
	Code               string // 예: "CURR_MATH_COMMON"
	Name               string // 예: "수학"
	ClassificationCode string // 상위 '교과구분종류'의 Code
}

// NaesinRawSubject: 특정 '교과'에 속하는 '과목'의 원본 데이터 (과목명만 저장)
// SubjectCode는 "NAESIN_" + Name 형태로 동적 생성됩니다.
type NaesinRawSubject struct {
	Name           string // 예: "수학Ⅰ"
	CurriculumCode string // 상위 '교과'의 Code
}

// --- 하드코딩 데이터 영역 ---
// 사용자가 여기에 실제 데이터를 채워 넣습니다.

// 교과구분종류 목록
var naesinClassificationsData = []NaesinCurriculumClassification{
	{Code: "CLASS_COMMON_SELECT", Name: "일반선택"},
	{Code: "CLASS_CAREER_SELECT", Name: "진로선택"},
	{Code: "CLASS_SCIENCE_QUEST", Name: "과학탐구실험"},
	// 추가 교과구분종류...
}

// 교과 목록
var naesinCurriculumsData = []NaesinCurriculum{

	{Code: "CURR_COMMON_KOR_SELECT", Name: "국어", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_MATH_SELECT", Name: "수학", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ENG_SELECT", Name: "영어", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_SOCIETY_SELECT", Name: "사회(역사/도덕포함)", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_SCIENCE_SELECT", Name: "과학", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_PE_SELECT", Name: "체육", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ART_SELECT", Name: "예술", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_INDUSTRY_SELECT", Name: "공업", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_OCEAN_SELECT", Name: "수산·해운", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_DESIGN_SELECT", Name: "디자인·문화콘텐츠", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_LEISURE_SELECT", Name: "미용·관광·레저", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_FOOD_SELECT", Name: "식품·가공", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ELECTRON_SELECT", Name: "전기·전자", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_CONSTRUCTION_SELECT", Name: "건설", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ECONOMY_SELECT", Name: "경영·금융", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_SCIENTIFIC_SELECT", Name: "과학 계열", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_CULTURE_SELECT", Name: "교양", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_INTERNATIONAL_SELECT", Name: "국제 계열", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_MECHANIC_SELECT", Name: "기계", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ECONOMY_SELECT", Name: "경영·금융", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT", Name: "농림·수산해양", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_HEALTH_WELFARE_SELECT", Name: "보건·복지", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_SHIP_OPERATION_SELECT", Name: "선박 운항", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_TEXTILE_CLOTHING_SELECT", Name: "섬유·의류", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ARTS_SELECT", Name: "예술 계열", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT", Name: "외국어 계열", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_FOOD_COOKING_SELECT", Name: "음식 조리", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT", Name: "인쇄·출판·공예", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_MATERIALS_SELECT", Name: "재료", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT", Name: "정보·통신", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT", Name: "제2외국어", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT", Name: "체육 계열", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_KOREAN_HISTORY_SELECT", Name: "한국사", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_CLASSICAL_CHINESE_SELECT", Name: "한문", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT", Name: "화학공업", ClassificationCode: "CLASS_COMMON_SELECT"},
	{Code: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT", Name: "환경·안전", ClassificationCode: "CLASS_COMMON_SELECT"},

	// 진로

	{Code: "CURR_COMMON_KOR_SELECT", Name: "국어", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_MATH_SELECT", Name: "수학", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_ENG_SELECT", Name: "영어", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_SOCIETY_SELECT", Name: "사회(역사/도덕포함)", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_SCIENCE_SELECT", Name: "과학", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_PE_SELECT", Name: "체육", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_ART_SELECT", Name: "예술", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_INDUSTRY_SELECT", Name: "공업", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_OCEAN_SELECT", Name: "수산·해운", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_DESIGN_SELECT", Name: "디자인·문화콘텐츠", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_LEISURE_SELECT", Name: "미용·관광·레저", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_FOOD_SELECT", Name: "식품·가공", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_ELECTRON_SELECT", Name: "전기·전자", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_CONSTRUCTION_SELECT", Name: "건설", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_ECONOMY_SELECT", Name: "경영·금융", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_SCIENTIFIC_SELECT", Name: "과학 계열", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_CULTURE_SELECT", Name: "교양", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_INTERNATIONAL_SELECT", Name: "국제 계열", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_MECHANIC_SELECT", Name: "기계", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT", Name: "농림·수산해양", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_HEALTH_WELFARE_SELECT", Name: "보건·복지", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_SHIP_OPERATION_SELECT", Name: "선박 운항", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_TEXTILE_CLOTHING_SELECT", Name: "섬유·의류", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_ARTS_SELECT", Name: "예술 계열", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT", Name: "외국어 계열", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_FOOD_COOKING_SELECT", Name: "음식 조리", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT", Name: "인쇄·출판·공예", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_MATERIALS_SELECT", Name: "재료", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT", Name: "정보·통신", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT", Name: "제2외국어", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT", Name: "체육 계열", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_KOREAN_HISTORY_SELECT", Name: "한국사", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_CLASSICAL_CHINESE_SELECT", Name: "한문", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT", Name: "화학공업", ClassificationCode: "CLASS_CAREER_SELECT"},
	{Code: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT", Name: "환경·안전", ClassificationCode: "CLASS_CAREER_SELECT"},

	// 과탐실

	{Code: "CURR_SCIENCE_QUEST_SELECT", Name: "과학", ClassificationCode: "CLASS_SCIENCE_QUEST"},
}

// (내신) 과목 목록 (과목명만 정의, 코드는 "NAESIN_과목명"으로 생성)
var naesinRawSubjectsData = []NaesinRawSubject{
	// 공통 교과 과목
	{Name: "과학탐구실험", CurriculumCode: "CURR_SCIENCE_QUEST_SELECT"},
	{Name: "국어Ⅰ", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "국어Ⅱ", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "화법과 작문", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "독서와 문법", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "문학", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "고전", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "국어", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "현대문학감상", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "독서", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "실용 국어", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "언어와매체", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "심화국어", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "고전 읽기", CurriculumCode: "CURR_COMMON_KOR_SELECT"},
	{Name: "기초 수학", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "수학Ⅰ", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "수학Ⅱ", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "확률과 통계", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "미적분Ⅰ", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "미적분Ⅱ", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "기하와 벡터", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "고급 수학Ⅰ", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "고급 수학Ⅱ", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "수학", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "미적분", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "수학과제 탐구", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "경제 수학", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "기하", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "실용 수학", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "기본 수학", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "인공지능 수학", CurriculumCode: "CURR_COMMON_MATH_SELECT"},
	{Name: "기초 영어", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "실용 영어Ⅰ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "실용 영어Ⅱ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "실용 영어 회화", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "실용 영어 독해와 작문", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영어Ⅰ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영어Ⅱ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영어 회화", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영어 독해와 작문", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "심화 영어", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "심화 영어 회화Ⅰ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "심화 영어 회화Ⅱ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "심화 영어 독해Ⅰ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "심화 영어 독해Ⅱ", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "심화 영어 작문", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영어", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "실용 영어", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영미문학읽기", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "진로영어", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "영어권 문화", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "기본 영어", CurriculumCode: "CURR_COMMON_ENG_SELECT"},
	{Name: "한국지리", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "세계지리", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "한국사", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "동아시아사", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "세계사", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "경제", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "법과 정치", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "사회·문화", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "국제 정치", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "국제 경제", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "국제 관계와 국제 기구", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "세계 문제", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "비교 문화", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "사회 과학 방법론", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "한국의 사회와 문화", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "국제법", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "지역 이해", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "인류의 미래 사회", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "생활과 윤리", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "윤리와 사상", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "과제 연구", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "사회", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "도덕", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "통합사회", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "정치와 법", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "사회문제 탐구", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "여행지리", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "고전과 윤리", CurriculumCode: "CURR_COMMON_SOCIETY_SELECT"},
	{Name: "과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "물리Ⅰ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "물리Ⅱ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "화학Ⅰ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "화학Ⅱ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "생명과학Ⅰ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "생명과학Ⅱ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "지구과학Ⅰ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "지구과학Ⅱ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "고급 물리", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "물리 실험", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "고급 화학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "화학 실험", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "고급 생명 과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "생명 과학 실험", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "고급 지구 과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "지구 과학 실험", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "환경 과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "과학사 및 과학 철학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "정보 과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "과제 연구", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "융합과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "통합과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "생활과 과학", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "과학사", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "물리학Ⅰ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "물리학Ⅱ", CurriculumCode: "CURR_COMMON_SCIENCE_SELECT"},
	{Name: "운동과 건강 생활", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠 문화", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠 과학", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠 개론", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "체육과 진로 탐구", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "육상 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "체조 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "수상 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "개인 및 대인 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "단체 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "체력 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "투기 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "빙상 및 설상 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "표현 및 창작 운동", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠경기 체력", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠경기 기술", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠경기 실습", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "코칭론", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠경영·행정", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "체육 전공 실기", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "전공 지도 실습", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "체육", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "운동과 건강", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "스포츠 생활", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "체육 탐구", CurriculumCode: "CURR_COMMON_PE_SELECT"},
	{Name: "무용의 이해", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "기초 한국 무용", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "기초 발레", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "기초 현대 무용", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "무용 전공 실기", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "무용 음악", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "무용 감상과 비평", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "안무", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "문학 개론", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "문장론", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "고전 문학 감상", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "현대 문학 감상", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "시 창작 입문", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "소설 창작 입문", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "문예 창작 전공 실기", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "연극의 이해", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "연기", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "무대 기술", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "연극 제작 실습", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "연극 감상과 비평", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "영화의 이해", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "영화기술", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "영화 창작과 표현", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "영화 제작 실습", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "영화 감상과 비평", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "사진의 이해", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "기초 촬영", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "중급 촬영", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "암실 실기", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "사진 편집", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "디지털 사진 촬영", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "디지털 사진 표현 기법", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "사진 감상과 비평", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "음악 감상과 비평", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "미술", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "미술 감상과 비평", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "미술 창작", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "연극 음악 연주", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "음악", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "연극", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "음악 연주", CurriculumCode: "CURR_COMMON_ART_SELECT"},
	{Name: "공업 일반", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전문 제도", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "기계 공작법", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "공작 기계", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전자 기계 회로", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "로봇 제작", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "주조", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전력 설비", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전자 회로", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "정보 통신", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "프로그래밍", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "토목 설계", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "지적 실무", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "건축 목공", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "색채 관리", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "시각 디자인", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "제조 화학", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "세라믹 원리·공정", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "식품 공업 기술", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "염색·가공", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "제판 실제", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "자동차 섀시", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "선박 이론", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "항공기 기체", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "인간과 환경", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "컴퓨터 게임 기획", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "애니메이션 제작", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "방송 시스템", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "기초 제도", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "기계 일반", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "유체 기계", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "산업 설비", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전자 기계 공작", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "재료 일반", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "금속 처리", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전기·전자 측정", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전자 기기", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "통신 시스템", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "디지털 논리 회로", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "토목 재료·시공", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "공간 정보", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "건축 구조체 시공", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "조형", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "컴퓨터 그래픽", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "분석 화학", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "스마트 세라믹", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "섬유 재료", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "인쇄의 이해", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "사진", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "자동차전기·전자제어", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "선박 구조", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "항공기 기관", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "수질 관리", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "컴퓨터 게임 프로그래밍", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "만화 창작", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "정보기술과 활용", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "전기와 생활", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "공기 조화 설비", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "금형 제작", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "공업계열", CurriculumCode: "CURR_COMMON_INDUSTRY_SELECT"},
	{Name: "수산 일반", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산 생물", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "양식 생물 질병", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "냉동 일반", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "선박 보조 기계", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "항해", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "선화 운송", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "생선회 실무", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양 플랜트 일반", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해사 일반", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산 경영 일반", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산 가공", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "냉동 공조 기기", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "선박 전기·전자", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "선박 운용", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "전자 통신 기초", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양 레저·관광", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양의 이해", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양 생산 기술", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산물 유통", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "냉동 공조 실무", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "기계 설계·공작", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해사 법규", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "전자 통신 기기", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양 물류 일반", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산·해운 산업 기초", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산 양식", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양 오염·방제", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "열기관", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "잠수 기술", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해사 영어", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "전자 통신 운용", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "해양 정보 관리", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "수산·해운계열", CurriculumCode: "CURR_COMMON_OCEAN_SELECT"},
	{Name: "광고 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "게임 기획", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "게임 디자인", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "게임 프로그래밍", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "디자인 일반", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "디자인 제도", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "디지털 디자인", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "만화 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "문화 콘텐츠 산업 일반", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "미디어 콘텐츠 일반", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "방송 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "색채 관리", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "색채 디자인", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "스마트 문화 앱 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "시각 디자인", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "실내 디자인", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "애니메이션 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "영상 제작 기초", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "영화 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "음악 콘텐츠 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "제품 디자인", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "조형", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "캐릭터 제작", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "컴퓨터 그래픽", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "디자인·문화 콘텐츠계열", CurriculumCode: "CURR_COMMON_DESIGN_SELECT"},
	{Name: "호텔 식음료 서비스 실무", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "관광 사업", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "관광 서비스", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "관광 영어", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "관광 일반", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "관광 일본어", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "관광 중국어", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "네일 미용", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "메이크업", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "미용 안전·보건", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "미용의 기초", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "여행 서비스 실무", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "유원 시설 서비스 실무", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "카지노 서비스 실무", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "피부 미용", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "헤어 미용", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "호텔 객실 서비스 실무", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "미용·관광·레저계열", CurriculumCode: "CURR_COMMON_LEISURE_SELECT"},
	{Name: "식품 위생", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "건강 기능 식품 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "곡물 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "김치·반찬 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "농산 식품 유통", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "농산 식품 저장", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "두류 식품 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "떡 제조", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "면류 식품 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "수산 식품 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "식품 가공 기술", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "식품 과학", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "식품 분석", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "식품 품질 관리", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "유제품 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "음료·주류 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "제과", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "제빵", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "축산 식품 가공", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "식품 가공계열", CurriculumCode: "CURR_COMMON_FOOD_SELECT"},
	{Name: "전자 부품 생산", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 부품 기구 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "정보 통신 기기 기구 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "직류 송배전 제어 ·보호 시스템 설비 제작", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "철도 신호 제어 시공", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "철도 신호 제어 시설물 유지 보수", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "화력 발전 설비 운영", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "3D 프린터 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "3D 프린터용 제품 제작", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "LED 기술 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "가상 훈련 구동 엔지니어링", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "가상 훈련 시스템 설계·검증", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "가전 기기 기구 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "가전 기기 시스템 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "가전 기기 응용 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "가전 기기 하드웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "광부품 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "내선 공사", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "디스플레이 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "디스플레이 생산", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "디스플레이 장비 부품 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "디지털 논리 회로", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "레이저 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "로봇 기구 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "로봇 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "로봇 유지 보수", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "로봇 지능 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "로봇 하드웨어 설계", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "반도체 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "반도체 장비", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "반도체 재료", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "반도체 제조", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "변전 설비 공사", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "산업용 전자 기기 기구 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "산업용 전자 기기 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "산업용 전자 기기 하드웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "송·변전 배전 설비 운영", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "수력 발전 설비 운영", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "외선 공사", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "원자력 발전 설비 운영", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "원자력 발전 전기 설비 정비", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "의료 기기 생산", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "의료 기기 연구·개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "의료 기기 인허가", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "자동 제어 기기 제작", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "자동 제어 시스템 운영", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "자동 제어 시스템 유지 정비", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "자동화 설비", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 기기", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 기기 설계", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 기기 유지 보수", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 기기 제작", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 설비", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 설비 운영", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 철도 시공", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 철도 시설물 유지 보수", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기 회로", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기·전자 기초", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기·전자 측정", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 부품 기획", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 부품 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 응용 기기 기구 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 응용 기기 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 응용 기기 하드웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 제품 기획", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 제품 생산", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 제품 설치·정비", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 제품 영업", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전자 회로", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "정보 통신 기기 소프트웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "정보 통신 기기 하드웨어 개발", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "직류 송배전 전력 변환 설비 제작", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "전기·전자계열", CurriculumCode: "CURR_COMMON_ELECTRON_SELECT"},
	{Name: "건축 기초 실습", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "건축 도면 해석과 제도", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "건축 도장 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "건축 마감 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "건축 목공 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "건축 일반", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "경량 철골 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "공간 정보 구축", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "공간 정보 융합 서비스", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "공업 일반", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "기초 제도", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "단열·수장 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "조경", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "조경 관리", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "조경 설계", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "조경 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "지적", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "창호 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "철근 콘크리트 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "측량", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "토공·포장 시공", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "토목 기초 실습", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "토목 도면 해석과 제도", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "토목 일반", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "건설계열", CurriculumCode: "CURR_COMMON_CONSTRUCTION_SELECT"},
	{Name: "고객 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "공급망 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "공정 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "구매 조달", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "국제 상무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "금융 일반", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "기업 자원 통합 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "기업과 경영", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "노무 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "마케팅과 광고", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "매장 판매", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "무역 금융 업무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "물류 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "방문 판매", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "보험 모집", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "보험 일반", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "비서", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "비즈니스 영어", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "사무 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "사무 행정", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "상업 경제", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "성공적인 직업생활", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "세무 실무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "세무 일반", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "손해 사정", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "수출입 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "예산·자금", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "원산지 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "유통 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "유통 일반", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "인사", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "자재 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "전자 상거래 실무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "전자 상거래 일반", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "증권 거래 업무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "창구 사무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "창업 일반", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "총무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "카드 영업", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "커뮤니케이션", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "품질 관리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "회계 실무", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "회계 원리", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "회계 정보 처리 시스템", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "경영·금융계열", CurriculumCode: "CURR_COMMON_ECONOMY_SELECT"},
	{Name: "고급 물리학", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "고급 생명과학", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "고급 수학Ⅰ", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "고급 수학Ⅱ", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "고급 지구과학", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "고급 화학", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "과학과제 연구", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "물리학 실험", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "생명과학 실험", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "생태와 환경", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "심화 수학Ⅰ", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "심화 수학Ⅱ", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "융합과학 탐구", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "정보과학", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "지구과학 실험", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "화학 실험", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "과학계열", CurriculumCode: "CURR_COMMON_SCIENTIFIC_SELECT"},
	{Name: "교육학", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "논리학", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "논술", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "보건", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "실용 경제", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "심리학", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "종교학", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "진로와 직업", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "철학", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "환경", CurriculumCode: "CURR_COMMON_CULTURE_SELECT"},
	{Name: "국제 경제", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "국제 관계와 국제기구", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "국제 정치", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "국제법", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "비교 문화", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "사회 탐구 방법", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "사회과제 연구", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "세계 문제와 미래 사회", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "지역 이해", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "한국 사회의 이해", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "현대 세계의 변화", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "국제계열", CurriculumCode: "CURR_COMMON_INTERNATIONAL_SELECT"},
	{Name: "건설 광산 기계 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "고무 플라스틱 기계 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "공작 기계 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계 기초 공작", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계 소프트웨어 개발", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계 수동 조립", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계 일반", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계 제도", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계 제어 설계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계요소 설계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기장 생산", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "냉동 공조 설계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "냉동 공조 유지·보수 관리", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "냉동 공조 일반", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "냉동 공조 장치 설치", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "농업용 기계 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "레이저 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "밀링 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "방전 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "보일러 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "보일러 장치 설치", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "사출 금형 설계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "사출 금형 제작", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "사출 금형 조립", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "사출 금형 품질 관리", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선박 건조", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선박 구조", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선박 도장", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선박 이론", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선반 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선실 의장 생산", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선장 생산", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선체 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선체 도면 독도와 제도", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선체 생산 설계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선체 조립", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "선체 품질 관리", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "섬유 기계 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "성형 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "소형 무인기 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "승강기 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "연삭 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "오토바이 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "운반 하역 기계 설치·정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "워터제트 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "유체 기계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 기관", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 도장", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 섀시", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 섀시 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 엔진 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 영업", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 일반", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 전기·전자 장치 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 전기·전자 제어", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 정비 검사", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 차체 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자동차 튜닝", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "자전거 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "전자 기계 이론", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "전장 생산", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "측정", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "컴퓨터 활용 생산", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "프레스 금형 설계", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "프레스 금형 제작", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "프레스 금형 조립", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "프레스 금형 품질 관리", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "플라스마 가공", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 가스 터빈 엔진 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 계통 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 기체 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 기체 제작", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 실무 기초", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 엔진·프로펠러 제작", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 왕복 엔진 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 일반", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 전기·전자 장비 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 전기·전자 장비 제작", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 정비 관리", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "항공기 프로펠러 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "헬리콥터 정비", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "기계계열", CurriculumCode: "CURR_COMMON_MECHANIC_SELECT"},
	{Name: "가금 사육", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "과수 재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "관광 농업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "근해 어업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "내수면 양식", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "내수면 어업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농산 식품 가공", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농산물 거래", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농산물 유통", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농산물 유통 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농산물 품질 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 경영", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 기계", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 기계 공작", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 기계 운전･작업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 기초 기술", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 생산 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 생산 환경 조성", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 정보 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 토목 시공･측량", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 토목 제도･설계", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업과 물", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농촌 체험 상품 개발", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농촌 체험 시설 운영", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농촌과 농지 개발", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "동물 약품 제조", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "동물 자원", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "돼지 사육", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "말 사육", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "목재 가공", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "바이오 의약품 제조", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "반려동물 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "버섯 재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "사료 생산", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "산림 보호", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "산림 자원", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "산림 조성", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "산림 휴양", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "산업 잠수", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "생명 공학 기술", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "생산 자재", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수도작 재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산 경영", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산 생물", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산 생물 질병 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산 양식 일반", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산 일반", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산 종묘 생산", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산물 유통", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수산･해운 산업 기초", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수상 레저 기구 조정", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "수의 보조", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "실험 동물과 기타 가축", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "애완동물 미용", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "양식 생물 질병", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "어업 자원 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "어업 환경 개선", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "어촌 체험 상품 개발", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "어촌 체험 시설 운영", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "연안 어업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "염 생산", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "요트 조종", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "원양 어업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "원예", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "육종", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "일반 잠수", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "임산 가공", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "임산물 생산", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "임업 종묘", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "잠수 기술", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "전자 통신 기초", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "전자 통신 운용", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "전특작 재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "젖소 사육", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "조경 식물 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "종자 생산", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "종자 유통 보급", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "종축", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "채소 재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "친환경 농업", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "펄프･종이 제조", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "한우 사육", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해면 양식", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양 레저 관광", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양 생산 일반", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양 오염･방제", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양 정보 관리", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양 환경과 자원", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "해양의 이해", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "화훼 장식", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "화훼 장식 기초", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "화훼 재배", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "환경 보전", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농업 이해", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "농림·수산계열", CurriculumCode: "CURR_COMMON_AGRICULTURE_FISHERIES_OCEAN_SELECT"},
	{Name: "간호의 기초", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "공중 보건", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "기초 간호 임상 실무", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "대인 복지 서비스", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "보건 간호", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "보육 과정", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "보육 실습", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "보육 원리와 보육 교사", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "복지 서비스의 기초", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "사회 복지 시설 실무", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "사회 복지 시설의 이해", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "생활 서비스 산업의 이해", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "아동 복지", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "아동 생활 지도", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "영·유아 건강·안전·영양 지도", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "영·유아 교수 방법", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "영·유아 놀이 지도", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "인간 발달", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "인체 구조와 기능", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "보건·복지계열", CurriculumCode: "CURR_COMMON_HEALTH_WELFARE_SELECT"},
	{Name: "기관 실무 기초", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "기관 직무 일반", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "기관사 직무", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 갑판 관리", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 기관 정비", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 기기 운용", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 보조 기계", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 보조기계 정비", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 안전 관리", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 운용", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 운항 관리", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 전기･전자", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 통신", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선화 운송", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "열기관", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "항만 물류 일반", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "항해 기초", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "항해사 직무", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "해사 법규", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "해사 영어", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "해사 일반", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "해운 일반", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "선박 운항계열", CurriculumCode: "CURR_COMMON_SHIP_OPERATION_SELECT"},
	{Name: "가죽·모피 디자인과 생산", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "구매 생산 관리", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "니트 의류 생산", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "방사·사가공", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "방적", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "비주얼 머천다이징", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "생산 현장 관리", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "서양 의복 구성과 생산", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "섬유 공정", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "섬유 재료", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "염색·가공", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "염색·가공 기초", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "의류 재료 관리", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "의복 구성의 기초", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "제포", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "텍스타일 디자인", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "패션 디자인의 기초", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "패션 디자인의 실제", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "패션 마케팅", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "패션 상품 유통 관리", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "패션 소품 디자인과 생산", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "패턴 메이킹", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "한국 의복 구성과 생산", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "섬유·의류계열", CurriculumCode: "CURR_COMMON_TEXTILE_CLOTHING_SELECT"},
	{Name: "고전문학 감상", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "공연실습", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "극 창작", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "기초 촬영", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "드로잉", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "매체 미술", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무대기술", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용 감상과 비평", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용 기초 실기", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용 음악 실습", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용 전공 실기", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용과 매체", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용과 몸", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "무용의 이해", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "문예 창작 입문", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "문장론", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "문학 개론", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "문학과 매체", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "미술 이론", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "미술 전공 실기", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "미술사", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "사진 감상과 비평", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "사진 영상 편집", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "사진 표현 기법", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "사진의 이해", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "소설 창작", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "시 창작", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "시나리오", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "시창·청음", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "안무", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "암실 실기", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "연극 감상과 비평", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "연극 제작 실습", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "연극의 이해", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "연기", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "영상 제작의 이해", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "영화 감상과 비평", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "영화 제작 실습", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "영화기술", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "영화의 이해", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "음악 전공 실기", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "음악사", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "음악이론", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "입체 조형", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "중급 촬영", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "평면 조형", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "합주", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "합창", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "현대문학 감상", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "예술계열", CurriculumCode: "CURR_COMMON_ARTS_SELECT"},
	{Name: "독일어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "독일어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "독일어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "독일어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "독일어권 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어권 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어 독해Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어 독해Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "심화 영어Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 독일어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 러시아어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 베트남어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 스페인어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 아랍어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 일본어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 중국어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "전공 기초 프랑스어", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어 독해와 작문Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어 독해와 작문Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어 회화Ⅰ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어 회화Ⅱ", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어권 문화", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "외국어 계열", CurriculumCode: "CURR_COMMON_FOREIGN_LANGUAGE_SELECT"},
	{Name: "급식 관리", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "바리스타", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "바텐더", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "서양 조리", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "소믈리에", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "식품과 영양", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "일식 조리", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "중식 조리", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "한국 조리", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "음식 조리계열", CurriculumCode: "CURR_COMMON_FOOD_COOKING_SELECT"},
	{Name: "공예 일반", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "공예 재료와 도구", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "귀금속·보석 디자인", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "금속 공예", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "도자기 공예", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "디지털 이미지 재현", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "목공예", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "보석 감정", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "석공예", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "섬유 공예", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "인쇄 일반", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "출판 일반", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "출판 편집", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "특수 인쇄", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "평판 인쇄", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "프리프레스", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "후가공", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "인쇄·출판·공예계열", CurriculumCode: "CURR_COMMON_PRINTING_PUBLISHING_CRAFT_SELECT"},
	{Name: "가스 텅스텐 아크 용접", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "광학 재료", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "금속 열처리", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "금속 재료 가공", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "금속 재료 신뢰성 시험", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "내열 구조 재료", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "내화물", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "도금", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "도자기", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "로봇 용접", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "배관 시공", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "비철 금속 제련", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "산업 설비", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "생체 세라믹 재료", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "서브머지드 아크 용접", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "세라믹 원리·공정", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "세라믹 재료", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "시멘트", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "압연", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "연삭재", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "유리·법랑", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "이산화탄소·가스 메탈 아크 용접", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "재료 시험", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "재료 일반", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "전기·전자 재료", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "제강", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "제선", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "주조", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "탄소 제품", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "판금 제관", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "피복 아크 용접", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "재료계열", CurriculumCode: "CURR_COMMON_MATERIALS_SELECT"},
	{Name: "네트워크 구축", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "네트워크 프로그래밍", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "데이터베이스 프로그래밍", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "무선 통신 구축", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "방송 일반", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "방송 제작 시스템 운용", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "빅데이터 분석", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "사물 인터넷 서비스 기획", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "시스템 관리 및 지원", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "시스템 프로그래밍", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "유선 통신 구축", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "응용 프로그래밍 개발", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "응용 프로그래밍 화면 구현", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "자료 구조", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "정보 보호 관리", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "정보 처리와 관리", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "정보 통신", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "초고속망 서비스 관리 운용", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "컴퓨터 구조", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "컴퓨터 네트워크", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "컴퓨터 보안", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "컴퓨터 시스템 일반", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "통신 시스템", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "통신 일반", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "프로그래밍", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "정보·통신계열", CurriculumCode: "CURR_COMMON_INFORMATION_COMMUNICATION_SELECT"},
	{Name: "독일어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "독일어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "러시아어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "베트남어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "스페인어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "아랍어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "일본어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "중국어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어Ⅰ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "프랑스어Ⅱ", CurriculumCode: "CURR_COMMON_SECOND_FOREIGN_LANGUAGE_SELECT"},
	{Name: "개인·대인 운동", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "단체 운동", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "수상 운동", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "스포츠 개론", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "스포츠 경기 분석", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "스포츠 경기 실습", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "스포츠 경기 체력", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "육상 운동", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체육 전공 실기 기초", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체육 전공 실기 심화", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체육 전공 실기 응용", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체육 지도법", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체육과 진로 탐구", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체조 운동", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "체육계열", CurriculumCode: "CURR_COMMON_PHYSICAL_EDUCATION_SELECT"},
	{Name: "한국사", CurriculumCode: "CURR_COMMON_KOREAN_HISTORY_SELECT"},
	{Name: "한문Ⅰ", CurriculumCode: "CURR_COMMON_CLASSICAL_CHINESE_SELECT"},
	{Name: "한문Ⅱ", CurriculumCode: "CURR_COMMON_CLASSICAL_CHINESE_SELECT"},
	{Name: "고분자 제품 제조", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "공업 화학", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "기능성 정밀 화학 제품 제조", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "단위 조작", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "무기 공업 화학", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "바이오 화학 제품 제조", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "석유 화학 제품", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "제조 화학", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "플라스틱 제품 제조", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "화학 공정 유지 운영", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "화학 물질 관리", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "화학 분석", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "화학 공업계열", CurriculumCode: "CURR_COMMON_CHEMICAL_INDUSTRY_SELECT"},
	{Name: "가스 안전 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "건설 안전 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "기계 안전 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "대기 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "산업 안전 보건 기초", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "산업 환경 보건", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "소음 진동 측정", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "수질 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "인간과 환경", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "전기 안전 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "폐기물 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "화공 안전 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "환경 생태 관리", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "환경 화학 기초", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
	{Name: "환경·안전계열", CurriculumCode: "CURR_COMMON_ENVIRONMENT_SAFETY_SELECT"},
}

// 수능 과목명 목록 (코드는 "SUNEUNG_과목명"으로 생성)
var suneungKoreanRawSubjectNames = []string{"화법과 작문", "언어와 매체"}
var suneungMathRawSubjectNames = []string{"확률과 통계", "미적분", "기하"}
var suneungSocialTamguRawSubjectNames = []string{
	"생활과 윤리", "윤리와 사상", "한국지리", "세계지리", "동아시아사", "세계사", "정치와 법", "경제", "사회·문화",
}
var suneungScienceTamguRawSubjectNames = []string{
	"물리학Ⅰ", "화학Ⅰ", "생명과학Ⅰ", "지구과학Ⅰ", "물리학Ⅱ", "화학Ⅱ", "생명과학Ⅱ", "지구과학Ⅱ",
}

// --- 핸들러 함수 ---
func Subject(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "GET 요청만 허용됩니다.", http.StatusMethodNotAllowed)
		return
	}

	subjectType := r.URL.Query().Get("type")
	classificationCode := r.URL.Query().Get("classificationCode") // Optional
	curriculumCode := r.URL.Query().Get("curriculumCode")         // Optional

	var results []ApiSubjectInfo

	switch subjectType {
	case "naesin_curriculum_classifications":
		for _, class := range naesinClassificationsData {
			results = append(results, ApiSubjectInfo{
				SubjectCode: class.Code,
				SubjectName: class.Name,
				ParentCode:  nil, // 최상위이므로 ParentCode 없음
			})
		}

	case "naesin_curriculums_for_classification":
		if classificationCode == "" {
			http.Error(w, "type이 'naesin_curriculums_for_classification'일 때 classificationCode 파라미터가 필요합니다.", http.StatusBadRequest)
			return
		}
		for _, curr := range naesinCurriculumsData {
			if curr.ClassificationCode == classificationCode {
				parentC := curr.ClassificationCode // 할당 후 주소 전달
				results = append(results, ApiSubjectInfo{
					SubjectCode: curr.Code,
					SubjectName: curr.Name,
					ParentCode:  &parentC,
				})
			}
		}

	case "naesin_subjects_for_curriculum":
		if curriculumCode == "" {
			http.Error(w, "type이 'naesin_subjects_for_curriculum'일 때 curriculumCode 파라미터가 필요합니다.", http.StatusBadRequest)
			return
		}
		for _, subj := range naesinRawSubjectsData {
			if subj.CurriculumCode == curriculumCode {
				parentC := subj.CurriculumCode // 할당 후 주소 전달
				results = append(results, ApiSubjectInfo{
					SubjectCode: "NAESIN_" + strings.ReplaceAll(subj.Name, " ", "_"), // 예: "NAESIN_수학Ⅰ", "NAESIN_화법과_작문"
					SubjectName: subj.Name,
					ParentCode:  &parentC,
				})
			}
		}

	case "naesin_subjects_all":
		for _, subj := range naesinRawSubjectsData {
			parentC := subj.CurriculumCode
			results = append(results, ApiSubjectInfo{
				SubjectCode: "NAESIN_" + strings.ReplaceAll(subj.Name, " ", "_"),
				SubjectName: subj.Name,
				ParentCode:  &parentC,
			})
		}

	case "suneung_국어":
		for _, name := range suneungKoreanRawSubjectNames {
			results = append(results, ApiSubjectInfo{
				SubjectCode: "SUNEUNG_" + strings.ReplaceAll(name, " ", "_"),
				SubjectName: name,
				ParentCode:  nil,
			})
		}

	case "suneung_수학":
		for _, name := range suneungMathRawSubjectNames {
			results = append(results, ApiSubjectInfo{
				SubjectCode: "SUNEUNG_" + strings.ReplaceAll(name, " ", "_"),
				SubjectName: name,
				ParentCode:  nil,
			})
		}

	case "suneung_탐구":
		for _, name := range suneungSocialTamguRawSubjectNames {
			results = append(results, ApiSubjectInfo{
				SubjectCode: "SUNEUNG_" + strings.ReplaceAll(name, " ", "_"), // 필요시 "SUNEUNG_사회탐구_" 등으로 Prefix 구분 가능
				SubjectName: name,
				ParentCode:  nil,
			})
		}
		for _, name := range suneungScienceTamguRawSubjectNames {
			results = append(results, ApiSubjectInfo{
				SubjectCode: "SUNEUNG_" + strings.ReplaceAll(name, " ", "_"), // 필요시 "SUNEUNG_과학탐구_" 등으로 Prefix 구분 가능
				SubjectName: name,
				ParentCode:  nil,
			})
		}

	default:
		if subjectType == "" {
			http.Error(w, "type 파라미터가 필요합니다.", http.StatusBadRequest)
		} else {
			// 유효하지 않은 type의 경우 빈 배열 반환 (또는 404 Not Found)
			// http.Error(w, "유효하지 않은 type 값입니다: "+subjectType, http.StatusNotFound)
			log.Printf("유효하지 않은 type 값 수신: %s", subjectType)
		}
		// results는 이미 빈 슬라이스로 초기화되어 있음
	}

	w.Header().Set("Content-Type", "application/json")
	// results가 비어있더라도 성공(200)으로 간주하고 빈 배열 []을 반환합니다.
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(results); err != nil {
		log.Printf("JSON 인코딩 에러: %v", err)
	}
}
